name: Run Deploy Test

run-name: Deploy ${{ inputs.APP }} on ${{ inputs.ENV }} (${{ github.head_ref || github.ref_name }})

on:
  workflow_dispatch:
    inputs:
      APP:
        description: "Application to deploy"
        required: true
        type: choice
        options:
          - kepler
      ENV:
        description: "Environment to deploy"
        required: true
        type: choice
        options:
          - andromeda
          - draco
          - orion
          - pallaxs
          - lyra
          - homolog
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Deploy test
        run: echo ${{ inputs.ENV }}
